apiVersion: skaffold/v4beta12
kind: Config
build:
  artifacts:
    - image: us.gcr.io/ticketing-dev-450816/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
  # local:
  #   push: false
  googleCloudBuild:
    projectId: ticketing-dev-450816
manifests:
  rawYaml:
    - ./infra/k8s/*